### ISSUE TITLE
remove file extension and change column name

### ISSUE THREAD

**Issue by paes** [bioinformatics-ufsc/FastProtein#1]
At the top left, where the executions appear, remove the '.zip' extension and rename the column to 'Tasks'

**Comment by simoesrenato** [comment]
Thank you for your suggestion. The references to 'job' and 'run' have been standardized to 'task' elsewhere in the application as well. The updated version is now available on Docker Hub and committed here on GitHub.

bioinfoufsc/fastprotein:latest
bioinfoufsc/fastprotein:interpro
